const EVENT_NAMESPACE = "ESCGameCustomizer";
const ACTION_FIELD_CHANGED = EVENT_NAMESPACE + ":ACTION_FIELD_CHANGED";
const ACTION_SET_SAVING = EVENT_NAMESPACE + ":ACTION_SET_SAVING";
const ACTION_SET_PUBLISHING = EVENT_NAMESPACE + ":ACTION_SET_PUBLISHING";
const ACTION_SET_PUBLISHABLE = EVENT_NAMESPACE + ":ACTION_SET_PUBLISHABLE";
const ACTION_SET_ESC = EVENT_NAMESPACE + ":ACTION_SET_ESC";
const ACTION_SET_VTT_DATA = EVENT_NAMESPACE + ":ACTION_SET_VTT_DATA";
const ACTION_SET_EXITING = EVENT_NAMESPACE + ":ACTION_SET_EXITING";
const ACTION_SET_SAVE_STATUS = EVENT_NAMESPACE + ":ACTION_SET_SAVE_STATUS";

export {
  EVENT_NAMESPACE,
  ACTION_FIELD_CHANGED,
  ACTION_SET_SAVING,
  ACTION_SET_PUBLISHING,
  ACTION_SET_PUBLISHABLE,
  ACTION_SET_ESC,
  ACTION_SET_VTT_DATA,
  ACTION_SET_EXITING,
  /**
   * true|false|undefined
   */
  ACTION_SET_SAVE_STATUS,
};
